import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def generate_pdf(
    transcript,
    reference_text,
    similarity,
    audio_features,
    filler_result,
    score,
    gemini_feedback,
):

    # ------------------------------------
    # Create reports folder
    # ------------------------------------

    os.makedirs("reports", exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    pdf_path = f"reports/analysis_report_{timestamp}.pdf"

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    story = []

    # ====================================
    # Title
    # ====================================

    story.append(
        Paragraph(
            "<b><font size=18>Voice-Based Concept Understanding Report</font></b>",
            styles["Title"],
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    story.append(
        Paragraph(
            f"<b>Date & Time:</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["BodyText"],
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    # ====================================
    # Student Transcript
    # ====================================

    story.append(
        Paragraph(
            "<b>Student Transcript</b>",
            styles["Heading2"],
        )
    )

    story.append(
        Paragraph(
            transcript,
            styles["BodyText"],
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    # ====================================
    # Reference Concept
    # ====================================

    story.append(
        Paragraph(
            "<b>Reference Concept</b>",
            styles["Heading2"],
        )
    )

    story.append(
        Paragraph(
            reference_text,
            styles["BodyText"],
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    # ====================================
    # Results Table
    # ====================================

    table_data = [

        ["Metric", "Value"],

        ["Semantic Similarity", f"{similarity:.2f}%"],

        ["Final Score", f"{score['Final Score']:.2f}/100"],

        ["Grade", score["Grade"]],

        ["Duration", str(audio_features["Duration"])],

        ["Speech Rate", str(audio_features["Speech Rate"])],

        ["Pause Ratio", str(audio_features["Pause Ratio"])],

        ["RMS Energy", str(audio_features["RMS Energy"])],

        ["Zero Crossing Rate", str(audio_features["Zero Crossing Rate"])],

        ["Filler Count", str(filler_result["total_fillers"])],

        ["Filler Density", f"{filler_result['filler_density']}%"],

    ]

    table = Table(table_data, colWidths=[220, 180])

    table.setStyle(
        TableStyle(
            [

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("ALIGN", (0, 0), (-1, -1), "CENTER"),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("GRID", (0, 0), (-1, -1), 1, colors.black),

                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

                ("TOPPADDING", (0, 1), (-1, -1), 8),

            ]
        )
    )

    story.append(table)

    story.append(Spacer(1, 0.3 * inch))

    # ====================================
    # Overall Performance
    # ====================================

    story.append(
        Paragraph(
            "<b>Overall Performance</b>",
            styles["Heading2"],
        )
    )

    story.append(
        Paragraph(
            f"The student's overall performance is "
            f"<b>{score['Grade']}</b> "
            f"with a final score of "
            f"<b>{score['Final Score']:.2f}/100</b>.",
            styles["BodyText"],
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    # ====================================
    # Gemini AI Feedback
    # ====================================

    story.append(
        Paragraph(
            "<b>Gemini AI Feedback</b>",
            styles["Heading2"],
        )
    )

    story.append(
        Paragraph(
            gemini_feedback.replace("\n", "<br/>"),
            styles["BodyText"],
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    # ====================================
    # Footer
    # ====================================

    story.append(
        Paragraph(
            "<b>Generated by</b><br/>"
            "Voice-Based Concept Understanding Analyser<br/>"
            "SmartBridge Internship Project",
            styles["Italic"],
        )
    )

    doc.build(story)

    return pdf_path